# Generated by Django 4.2.1 on 2023-05-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('discord', 'Discord'), ('youtube', 'YouTube'), ('medium', 'Medium'), ('telegram', 'Telegram'), ('etsy', 'Etsy'), ('twitch', 'Twitch'), ('reddit', 'Reddit'), ('patreon', 'Patreon'), ('flickr', 'Flickr')], max_length=100),
        ),
    ]
