# Generated by Django 4.2.1 on 2023-05-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_link_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='username',
            new_name='handle',
        ),
        migrations.AddField(
            model_name='link',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('discord', 'Discord'), ('youtube', 'YouTube'), ('medium', 'Medium'), ('telegram', 'Telegram'), ('etsy', 'Etsy'), ('twitch', 'Twitch'), ('reddit', 'Reddit'), ('patreon', 'Patreon'), ('flickr', 'Flickr'), ('other', 'Other')], max_length=100),
        ),
    ]
